### ISSUE TITLE
QuickRender option acts weird on .tpl extension file

### ISSUE THREAD

**Issue by Vistritium** [MachinePublishers/jBrowserDriver#131]
QuickRender option is set to true.
When the url of the http server is remote, the .tpl extension file is discarded.
When the ulr is local server, .tpl file is loaded.
When I set option quickRender to false, it is working fine on both remote and local and the .tpl is loaded.

.tpl is not a media file, it contains html and is needed by angular app.

I tried to debug the library to check exactly what is happening but apparently it runs in it's own process and I'm unable to debug it. Probably could start with debugging this: https://github.com/MachinePublishers/jBrowserDriver/blob/a396ff6b5361e9ef9b7d7e2a747ee0518b7838a4/src/com/machinepublishers/jbrowserdriver/ResponseHandler.java#L95

**Comment by hollingsworthd** [comment]
Thanks. I never really use debuggers, but FYI it launches a Java process and then uses RMI to communicate with it.

The problem is probably [here](https://github.com/MachinePublishers/jBrowserDriver/blob/master/src/com/machinepublishers/jbrowserdriver/StreamConnection.java#L177) where it looks at content type. I'll investigate what headers are coming back and adjust it.
