### ISSUE TITLE
All POST requests w/ entities broken

### ISSUE THREAD

**Issue by jjlauer** [MachinePublishers/jBrowserDriver#158]
Spent the better part of today tracking down an issue with an XHR POST request that continued to timeout.  It looks like any HTTP POST that includes a body (entity) is currently broken.  The issue is that HttpClient only sends an entity if the Request is an an instance of HttpEntityEnclosingRequest.  However, JBD wraps the HttpPost (request) twice in JbdExecChain.  The JbdRequest class doesn't implement the HttpEntityEnclosingRequest, so it never gets sent.

https://github.com/apache/httpcore/blob/4.4.x/httpcore/src/main/java/org/apache/http/protocol/HttpRequestExecutor.java#L206

I have a couple questions/comments as well.

Is decorating the request twice really the best way to strip out the "Via" header?  Is that header that important to strip out that we wrap the request & potentially cause bugs like this?

I would have submitted a PR with a unit test, but the project isn't really setup for unit testing.  You mentioned the diagnostics package previously, but something like this is much easier to troubleshoot directly.

I also spent a couple hours tracking it down due to RMI and the non-obvious way of running the browser code directly.  Have you ever considered letting you fire up a browser not using RMI?  It seems like unit testing for development would be easier by eliminating much of the selenium code in-between for somethings.

I'd be happy to help here, but I think it would require restructuring the project, tweaking the pom, etc.  Are you open to that?

**Comment by hollingsworthd** [comment]
Thank you for looking into that! The header is important to strip out because not all users want to advertise to target sites that they're making the request via HttpComponents. HttpComponents had a request/response interceptors but they never let you be the ultimate last interceptor--Via header always gets added. If you have a PR I will review it without unit tests. And I would welcome a PR to make the project run without RMI, but personally I'm not interested in making this all run on Junit or have unit-level tests--although if you want to do this and it doesn't interfere with how testing is currently done then that's fine. I commented on #123 about the flow and order of calls in the code.

Anyhow, thanks again for your help. I don't want to discourage contributions--I'll review anything and do my best to integrate whatever you'd like.

**Comment by hollingsworthd** [comment]
I figured out a way to avoid wrapping the requests/responses or extending the client builders. It now uses the HttpRequestExecutor in a way that's the intended use I think. Also added tests of HTTP post.

Also note for debugging, you can enable logging which captures all output from the RMI child process (in Test.java comment out the line `.logger(null)`). Additionally you can pass an argument to the child processes to open a socket for remote debugging `.javaOptions("-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n")`

**Comment by jjlauer** [comment]
Nice! Even better than what I had worked up https://github.com/jjlauer/jBrowserDriver/commit/f0415ebbd4315cec9e877ce488a7ec14d020393f
