### ISSUE TITLE
CookieManager

### ISSUE THREAD

**Issue by criticalbh** [MachinePublishers/jBrowserDriver#177]
It looks like this driver is using some com.sun libraries. Is it possible to refactor that?

**Comment by hollingsworthd** [comment]
References to com.sun.webkit.network.CookieManager can and should probably be replaced with java.net.CookieHandler.

Not sure of any simple way around usages of com.sun.glass.ui.*

Usages of com.sun.javafx.webkit.Accessor and com.sun.webkit.WebPage can probably be refactored.

And I'd imagine there's some way around using sun.net.www.protocol.* , com.sun.webkit.network.data.* and com.sun.webkit.network.about.* which are all protocol handlers.

That sums up all the internal Sun APIs that are used. If you're asking because of Java 9 try `Settings.builder().javaExportModules(true)` ... if you're wanting to use a non-Oracle JRE curious to know which.
