### ISSUE TITLE
sendKeys not working.

### ISSUE THREAD

**Issue by Kurimatzu** [MachinePublishers/jBrowserDriver#246]
List<WebElement> inputs = driver.findElementsByTagName("div");
   for (WebElement allIn : inputs) {
     if (allIn.getAttribute("class") != null) {
	if (allIn.getAttribute("class").equals("input")) {
	  System.out.println("eeeeeeeeeeeeeee");
		allIn.sendKeys("Teste");
	}
  }
}

I want to get a div that has the class input, and write some text in it, and send.

However, this code is not working. Nothing happens.

Is there any other way?

**Comment by hollingsworthd** [comment]
Not sure. If you look in https://github.com/MachinePublishers/jBrowserDriver/blob/master/src/com/machinepublishers/jbrowserdriver/diagnostics/test.htm it's a test html page and the `main` method in https://github.com/MachinePublishers/jBrowserDriver/blob/master/src/com/machinepublishers/jbrowserdriver/diagnostics/Test.java runs the tests. If you could create a test case that reproduces this issue that would help. Otherwise it's hard to know whether it's a bug. Thanks.

**Comment by Kurimatzu** [comment]
Is an error in the button.

See #247
