### ISSUE TITLE
Is there any way to switch to iframe?

### ISSUE THREAD

**Issue by evgeniynickolaev** [MachinePublishers/jBrowserDriver#3]
I see com.machinepublishers.jbrowserdriver.TargetLocator has only stub methods.
Do you have any draft of this?
Or could you please kindly advice how can it be implemented?

**Comment by hollingsworthd** [comment]
TargetLocator implements one method, to switch windows (e.g., ones created from popups). This functionality relies on BrowserContext and BrowserContextItem. BrowserContext holds the state for each instance of JBrowserDriver. BrowserContextItem holds the state for each window. So, a list of BrowserContextItems is maintained in BrowserContext.

I haven't considered yet how to implement iframes. This is all built on JavaFX's WebView classes, so it would involve exposing their functionality where possible.

If you're reading the source code, you've probably noticed that the code is littered with things like JavaFX.call("somemethod") instead of just using those classes directly. That's to support multiple instances of JBrowserDriver. JavaFX's WebView presumes that only one browser will ever be run, so I have to put each browser in it's own classloader and rely on dynamic classpath resolution at runtime.

I will add iframe support eventually but don't have a timeline of when yet. If I were to guess, it's on the order of months (not days, not years).

**Comment by evgeniynickolaev** [comment]
Thank you very much for the reply.
I wanted to implement it myself but saw it was rather difficult for me..

**Comment by hollingsworthd** [comment]
Frames are supported in Master now. Available in next release.
