### ISSUE TITLE
JBrowserDriver not found on OS X

### ISSUE THREAD

**Issue by doanchu** [MachinePublishers/jBrowserDriver#30]
Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer

The build for Windows has already fixed this problem. But it still persists on OS X.

**Comment by davegrow** [comment]
I'm getting this too.

**Comment by qqilihq** [comment]
Problem seems to be that the written classpath in the `classpath.jar`'s `MANIFEST.MF` looks like this:

    Manifest-Version: 1.0
    Class-Path: ../../../../../../Users/me/Code/jBrowserTest/target/classes/ …

But it should rather be `/Users/me/…`. Guess, replacing `relativize` by `resolve` on line 152 in JBrowserDriver should fix this isse?

**Comment by hollingsworthd** [comment]
Thanks for the info, everyone. I will look into this. Waiting on an Apple delivery to set up a test env...

**Comment by ashdsouza** [comment]
Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer
on Mac OSX 10.9. Using JBrowserDriver 0.9.1

**Comment by hollingsworthd** [comment]
@ashdsouza From my tests, jBrowserDriver 0.9.2 on OSX 10.11 works. Please confirm with 0.9.2 (there were changes related to this code in that release).

If it's still broken, please let me know more info, such as how your app is packaged, if it's on an app server, what Java version, etc.

FYI: the code responsible for this is https://github.com/MachinePublishers/jBrowserDriver/blob/cd6dab5822e378f1089f83d59ac754baac583659/src/com/machinepublishers/jbrowserdriver/JBrowserDriver.java#L129

**Comment by ashdsouza** [comment]
Tried 0.9.3. I dont see this issue. However, I do get the following exception.

`[Port 10000] Exception in Application start method
[Port 10000] [2016-02-22T11:21:05-0800] [WARNING] java.lang.RuntimeException: Exception in Application start method
[Port 10000] 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:894)
[Port 10000] 	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
[Port 10000] 	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
[Port 10000] 	at java.lang.Thread.run(Thread.java:745)
[Port 10000] Caused by: java.lang.IllegalAccessError: tried to access method com.sun.glass.ui.Screen.notifySettingsChanged()V from class com.machinepublishers.jbrowserdriver.App
[Port 10000] 	at com.machinepublishers.jbrowserdriver.App.start(App.java:112)
[Port 10000] 	at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
[Port 10000] 	at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
[Port 10000] 	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
[Port 10000] 	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
[Port 10000] 	at java.security.AccessController.doPrivileged(Native Method)
[Port 10000] 	at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
[Port 10000] 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
[Port 10000] 	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
[Port 10000] 	... 1 more
[Port 10000] 
`

**Comment by hollingsworthd** [comment]
@ashdsouza if you update to a more recent Java 8 version the issue will go away. I'll see about fixing it for the next release.
