### ISSUE TITLE
Make read timeouts configurable

### ISSUE THREAD

**Issue by hollingsworthd** [MachinePublishers/jBrowserDriver#52]

**Comment by ashdsouza** [comment]
Seeing this consistently while testing on Linux. Using v0.10.0 on JBrowserDriver.

`[Port 10000] Mar 02, 2016 6:39:01 PM com.sun.webkit.network.URLLoader doRun

[Port 10000] WARNING: Unexpected error

[Port 10000] java.io.IOException: Connect to 54.86.251.172:13000 [/54.86.251.172] failed: connect timed out: http://www.google.com/

[Port 10000] at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:320)

[Port 10000] at com.machinepublishers.jbrowserdriver.StreamConnection.getResponseCode(StreamConnection.java:427)

[Port 10000] at com.sun.webkit.network.URLLoader.receiveResponse(URLLoader.java:414)

[Port 10000] at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:163)

[Port 10000] at com.sun.webkit.network.URLLoader.lambda$run$91(URLLoader.java:128)

[Port 10000] at java.security.AccessController.doPrivileged(Native Method)

[Port 10000] at com.sun.webkit.network.URLLoader.run(URLLoader.java:127)

[Port 10000] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[Port 10000] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[Port 10000] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[Port 10000] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[Port 10000] at java.lang.Thread.run(Thread.java:745)

[Port 10000] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to 54.86.251.172:13000 [/54.86.251.172] failed: connect timed out

[Port 10000] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)

[Port 10000] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)

[Port 10000] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:388)

[Port 10000] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)

[Port 10000] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)

[Port 10000] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)

[Port 10000] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)

[Port 10000] at com.machinepublishers.jbrowserdriver.StreamConnectionClient.execute(StreamConnectionClient.java:151)

[Port 10000] at com.machinepublishers.jbrowserdriver.StreamConnection.exec(StreamConnection.java:312)

[Port 10000] ... 11 more

[Port 10000] Caused by: java.net.SocketTimeoutException: connect timed out

[Port 10000] at java.net.PlainSocketImpl.socketConnect(Native Method)

[Port 10000] at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

[Port 10000] at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

[Port 10000] at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

[Port 10000] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

[Port 10000] at java.net.Socket.connect(Socket.java:589)

[Port 10000] at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)

[Port 10000] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)

[Port 10000] ... 19 more

[Port 10000] `

**Comment by Radisvoik** [comment]
I hit this bugger all the time.:(

**Comment by suchitbiswal** [comment]
hollingsworthd is this issue fixed ? I am seeing this issue still in linux. Do I need to configure the timeout separately for this ?

**Comment by hollingsworthd** [comment]
@suchitbiswal yes it's configurable. When the work on this ticket was done the defaults didn't change, only the ability to configure them was added. So you'll want to see:

- [connectionReqTimeout](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#connectionReqTimeout-int-)
- [connectTimeout](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#connectTimeout-int-)
- [socketTimeout](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#socketTimeout-int-)

**Comment by ambition-consulting** [comment]
Still got this problem, despite setting the timeout to 60000 ms... I don't think this is really a timeout issue, despite what the Exception says... What works on windows, times out on Unix, despite same connectivity context.
