### ISSUE TITLE
unknown error on trying to load any  webpage

### ISSUE THREAD

**Issue by typhoid** [MachinePublishers/jBrowserDriver#61]
[Port 10000] Exception in thread "main" java.lang.NullPointerException
[Port 10000] 	at com.machinepublishers.jbrowserdriver.LogsServer.exception(LogsServer.java:110)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:97)

it also loads a new java.exe everytime i retry it confusing

**Comment by typhoid** [comment]
if i close all the java.exe instances i can get it to move beyond this error

**Comment by shackman0** [comment]
@typhoid When i first started using jBrowserDriver, i was neglecting to #quit(), particularly when my code threw an exception. failing to #quit() leaves the java process running. get enough of those and you'll get an error like this.

so that i wouldn't forget to call #quit(), i created a CloseableBrowserDriver wrapper for use in a try-with-resources block; whose #close() method calls the underlying browserdriver's #quit() method.

now, i don't have all those java processes hanging around, even when i have an exception in my code.

**Comment by hollingsworthd** [comment]
JBrowserDriver.quit() must be called. Not sure of any way to call quit automatically when a thread reaches its end.
